// Code generated by Slice Machine. DO NOT EDIT.

import Banner from './Banner';
import GalleryContent from './GalleryContent';
import GalleryMain from './GalleryMain';
import Image from './Image';
import Text from './Text';

export {
	Banner,
	GalleryContent,
	GalleryMain,
	Image,
	Text,
};

export const components = {
	banner: Banner,
	related_gallery: GalleryContent,
	gallery: GalleryMain,
	image: Image,
	text: Text,
};
