// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  desc_image: dynamic(() => import("./DescImage")),
  gallery: dynamic(() => import("./Gallery")),
  header_image: dynamic(() => import("./HeaderImage")),
  image: dynamic(() => import("./Image")),
  product: dynamic(() => import("./Product")),
  repeat_image: dynamic(() => import("./RepeatImage")),
  text: dynamic(() => import("./Text")),
};
